services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5555:5000" # mapping the external port 5555 to container's internal port 5000 (local - localhost:5555)
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: 'true'
      MAIL_USERNAME: 'bpsoftware16@gmail.com'
      MAIL_PASSWORD: 'crab kyyp dega hfcd'
      MAIL_DEFAULT_SENDER: 'bpsoftware16@gmail.com'
      MONGO_URI: mongodb://root:root@mongodb:27017
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3333:3000" # mapping the external port 3333 to container's internal port 3000 (local - localhost:3333)
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5555
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodata:/data
    command:
      - "--auth"
volumes:
  mongodata:
